### ISSUE TITLE
Breaking changes "shopping list"

### ISSUE THREAD

**Issue by mgold** [elm-community/elm-test#113]
This is a list of breaking changes we want to make, but don't justify a MAJOR version bump. Whenever we wind up doing such a bump, let's make sure these changes make it in.

* [x] Move `Expect.getFailure` to `Test.Runner`, because only the runners need to inspect expectation output, not people writing tests.
* [x] #95 Passing `[]` to `describe` should be a failed test
* [x] #117 Passing `""` to `describe` should be a failed test
* [x] #116 Rename `Fuzz.frequencyOrCrash` to `Fuzz.frequency`, supported by invalid fuzzers. Implemented by #122.
* [x] #133 Duplicate titles should cause test failures
* [x] rtfeldman/node-test-runner#104 Support TODO tests
* [x] Remove `Test.filter`
* [ ] rtfeldman/node-test-runner#105 Account for `getFailure` moving
* [ ] Ensure the html runner is up to date
* [ ] Update README, especially Upgrading section

**Comment by mgold** [comment]
Tagging as "release blocker" so we don't forget, but it's only a major release blocker.

**Comment by rtfeldman** [comment]
Since pretty almost all of these are in `master` now, moving remaining items to the more narrowly scoped https://github.com/elm-community/elm-test/issues/145 ! 🎉
