### ISSUE TITLE
Planning for 0.19 and 5.0.0

### ISSUE THREAD

**Issue by mgold** [elm-community/elm-test#191]
Although it's fair to question whether we should group API and language changes together. I'd be open to updating to 0.19 on the 4.x line, and following up with breaking API when we are good and ready. That will also help isolate bugs in the test runners.

Changes that need/should to be done for 0.19:
* [ ] Update the node runner to use `elm.json` and `test-dependencies` (@rtfeldman )
* [ ] Update the HTML runner to use `elm.json` and `test-dependencies` (@hkgumbs ?)
* [x] Use pure Elm for laziness (lazy package going away in 0.19) #184 (@eeue56)
* [x] Use core Random instead of 3rd party lib (@mgold)
  * elm-lang/core#887
* [x] Update dependencies
* [x] Convert `elm-package.json` to `elm.json`
* [ ] Update docs re: `elm.json`

Changes considered for 5.0.0:
* [x] Safer Test.Runner API #179 (@hkgumbs and @rtfeldman, maybe @zwilias)
* [x] Removing Fuzz.andThen, change Test.Runner.fuzz API #183 (ready to merge)
* [ ] Remove Fuzz.conditional (discussed on Slack)
* [ ] Update changelog

Punting:
* Issues with error messages, seem to be resolved by installing latest versions of everything (#178, #176, #181)
* Changes to how fuzzing/shrinking works, except for those that can be submitted to `elm-community/shrink` independently of elm-test
  * #199 is under consideration, but not a release blocker
* Other API additions that are MINOR changes

All of this is subject to community discussion and approval.

**Comment by rtfeldman** [comment]
I like this plan. No reason to block people from upgrading to 0.19 until
they find replacement solutions for what they're using `andThen` or
`conditional` for today.

So in 4.0.0 the only breaking change would be switching to `core` Random's
(equivalent, but technically different) types?

**Comment by mgold** [comment]
> So in 4.0.0

We've already released 4.0.0. 

Oh right, changing Random will be a breaking change. Technically, but not actually. Silly elm-package.

I want to avoid *two* major version bumps in the near future. I will work to make core/Random compatible with our needs. Then we'll swap over elm-test.

**Comment by rtfeldman** [comment]
Ha, good point about 4 being the current one. 😅

I'm okay with going to 5 for 0.19 and then 6 with more serious breaking
changes like taking out `andThen` and `conditional`.

We could actually move both of those to like `Test.Deprecated` for 5.0 so
people have a heads-up but can still upgrade easily if they're not ready to
switch yet.

**Comment by jwoudenberg** [comment]
@rtfeldman I definitely see the advantage for users of moving features to `Test.Deprecated`. The disadvantage I see is that while we have `andThen` in that module our fuzzers will not be statically analysable which would preclude some optimisations we might start thinking about.

**Comment by rtfeldman** [comment]
We can start working on those on an unreleased branch where `andThen` is
gone, yeah?

**Comment by rtfeldman** [comment]
Actually if deprecation is the plan, I kinda like the idea of making a
5.0.0 branch for 0.19 now, finalizing the changes (deprecation etc),
getting rid of `andThen` on master, and then continuing work on master for
6.0.

**Comment by mgold** [comment]
> I'm okay with going to 5 for 0.19 and then 6 with more serious breaking
changes like taking out `andThen` and `conditional`.

Are there any breaking changes absolutely required for 0.19 compatibility? I'm not sure there are any.

**Comment by rtfeldman** [comment]
Not if you publish an 0.19-compatible [`mgold/elm-random-pcg`](http://package.elm-lang.org/packages/mgold/elm-random-pcg/latest/Random-Pcg) release.

Otherwise [`Fuzz.custom`](http://package.elm-lang.org/packages/elm-community/elm-test/4.1.1/Fuzz#custom) currently takes a `Random.PcgGenerator`, and it'll take a `Random.Generator` instead if we switch to using `core`.

**Comment by mgold** [comment]
> Not if you publish an 0.19-compatible mgold/elm-random-pcg release.

I can do that. Give people (like us!) time to transition, and complain about anything that's different in core.

**Comment by rtfeldman** [comment]
Okay, that works for me.

That said, I think we're agreed that there will be a future release which removes `andThen`, so @jwoudenberg I think it's safe to continue (on a branch) under the assumption that this will happen post-0.19, yeah?

**Comment by Maxim-Filimonov** [comment]
Hi, found this after a quick try to use with 0.19. Are there plans to update this library to 0.19 ?

**Comment by mgold** [comment]
It's at `elm-explorations/test`. You'll also want `nom I -g elm-test@beta`.

I also think it's time to close this issue.
